// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjknuoordhiqvnfquwix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqa251b29yZGhpcXZuZnF1d2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjA4MDIsImV4cCI6MjA2NTQ5NjgwMn0.e8ZdilUaS10DWYxwjtTVnOdTRsGMN8Ps1IojKw8kHsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);